# Generated by Django 3.1.13 on 2021-11-17 17:29

from django.db import migrations


class Migration(migrations.Migration):

    def remove_images_from_db(apps, schema_editor):
        CustomCardImage = apps.get_model('create_cards', 'CustomCardImage')
        CustomCardImage.objects.filter(filename__startswith='abstract').delete()

    dependencies = [
        ('create_cards', '0002_auto_20211113_0331'),
    ]

    operations = [
        migrations.RunPython(remove_images_from_db),
    ]


