version: "3.8"

services:
  web:
    image: "${WEB_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile.prod
      cache_from:
        - "${WEB_IMAGE}"
    command: gunicorn deckzap.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    env_file: .env
  asgi:
    image: "${WEB_IMAGE}"
    command: daphne -b 0.0.0.0 -p 8000 deckzap.asgi:application
    env_file: .env
    depends_on:
      - web
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
      - asgi

volumes:
  static_volume:
  media_volume:
