version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - PROJECT_NAME=deckzap
      - SECRET_KEY=@03jdj6y-88#1=4p(p7xlmerm*jv)8rt5=^t!40@-2+=o3@i2)
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_DATABASE=django_db
      - SQL_USER=django
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
      - AMPLITUDE_API_KEY=fbe550d7a8776e824a58f01372900f74
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=django_db

volumes:
  postgres_data:
