# Generated by Django 3.1.2 on 2021-09-07 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('cards_hash', models.TextField()),
                ('deck_json', models.JSONField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_finished', models.DateField()),
                ('date_started', models.DateField()),
                ('player_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_one', to=settings.AUTH_USER_MODEL)),
                ('player_one_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_one_deck', to='battle_wizard.globaldeck')),
                ('player_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_two', to=settings.AUTH_USER_MODEL)),
                ('player_two_deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_two_deck', to='battle_wizard.globaldeck')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
