# Generated by Django 3.1.2 on 2021-09-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_wizard', '0002_auto_20210908_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='date_finished',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='date_started',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='globaldeck',
            name='date_created',
            field=models.DateTimeField(),
        ),
    ]
