# Generated by Django 3.1.2 on 2021-09-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_wizard', '0004_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaldeck',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
