# Generated by Django 3.1.2 on 2021-09-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_wizard', '0005_globaldeck_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaldeck',
            name='title',
        ),
        migrations.AddField(
            model_name='deck',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
