# Generated by Django 3.1.2 on 2021-09-08 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_wizard', '0006_auto_20210908_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 3, 57, 47, 516092)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='date_started',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='player_one_deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_one_deck', to='battle_wizard.globaldeck'),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='player_two_deck',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_two_deck', to='battle_wizard.globaldeck'),
        ),
    ]
