# Generated by Django 3.1.2 on 2021-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_wizard', '0008_gamerecord_game_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerecord',
            name='game_json',
            field=models.JSONField(default=dict),
        ),
    ]
