# Generated by Django 3.1.2 on 2021-10-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_wizard', '0010_customcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='battle_wizard.customcard')),
            ],
        ),
    ]
